# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if and .Values.ingress.enabled .Values.frontend.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openan-frontend-ingress
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "openan.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if and .Values.ingress.tls.enabled .Values.ingress.host }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host }}
      {{- end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: workflow-designer
                port:
                  number: {{ .Values.frontend.port }}
{{- end }}
---
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if and .Values.ingress.enabled .Values.orchestration.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openan-orchestration-ingress
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "openan.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestration
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if and .Values.ingress.tls.enabled .Values.ingress.host }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host }}
      {{- end }}
      http:
        paths:
          - path: /api/orchestrate(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: orchestration-center
                port:
                  number: {{ .Values.orchestration.port }}
{{- end }}
---
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if and .Values.ingress.enabled .Values.registry.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openan-registry-ingress
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "openan.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if and .Values.ingress.tls.enabled .Values.ingress.host }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host }}
      {{- end }}
      http:
        paths:
          - path: /registry(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: registry-center
                port:
                  number: {{ .Values.registry.port }}
{{- end }}
